### PR TITLE
PlaceholderAPI Support

### PR DESCRIPTION
**Pull request by Mitality**
- simplified and extracted stars/bar-generation
- added [PlaceholderAPI](https://www.spigotmc.org/resources/placeholderapi.6245/) as a softdependency
- added and registered a PlaceholderExpansion

Added PAPI Placeholders:
   %breweryx_drunkenness%
   %breweryx_drunkenness_bars%
   %breweryx_quality%
   %breweryx_quality_stars%

### CODE REVIEW

**Comment by Mitality** [comment]
+ added a config option for year length (aging)

**Comment by Mitality** [comment]
+ added a config option to disable the requirement of having a line on a barrel's sign say "barrel" (or a translation of it) and instead allow any text, or just no text at all

**Comment by Mitality** [comment]
+ added cut copper as a new barrel type (12) (supports all waxed/oxidized variants)

**Comment by Mitality** [comment]
Alright, done for the day🙂

**Comment by Mitality** [comment]
+ Fixed a bug allowing players to stack barrels internally by repeatedly breaking and placing the sign on the big version of a barrel

**Comment by Mitality** [comment]
+ Removed the non functional half-existing `/brew <player> <drunkenness> [quality]` command
+ Added a brand-new `/brew set <player> <drunkenness> [quality]` subcommand that works as intended

**Comment by Mitality** [comment]
+ Fixed missing required data class warning on 1.21. Depending on the servers game-version, particles are now generated in different ways to ensure compatibility with versions below

**Comment by Mitality** [comment]
+ Added an optional command scheduling for player and server commands executed onDrink. A delay can be specified by adding (another) '/' to the command and the delay in minutes or seconds (m or s) after that.

Heres my testconfiguration (an invalid delay defaults to 0):
servercommands:
      \- /gamemode survival %player_name% / 3s
      \- /gamemode creative %player_name%  /   6s
      \- /time set noon / -23s
playercommands:
      \- /say Quality %quality%/1m
      \- /say Quality %quality% /3m
      \- /say Immediately executed testmessage

**Comment by szarkans** [comment]
u are THE goat, bro

**Pull request merged**
